In [45]:
import pandas as pd

In [46]:
# 음식 db
db_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/식품db.xlsx"
food_db = pd.read_excel(db_path)
food_db = food_db.transpose()
food_db.rename(columns=food_db.iloc[0], inplace=True)
food_db.drop(index="식품명",inplace=True)

In [47]:
food_db

,배추김치,커피,탄산음료,잡곡밥,달걀부침/후라이,과자,쌈장,볶음밥/오므라이스,상추,단무지,...,된장,오징어젓,옥수수,아몬드,오이,고구마줄기나물,배,참외,호박나물,누룽지
에너지,38.0,2.0,36.090909,150.0,206.0,513.0,240.0,162.0,20.0,12.0,...,193.0,166.0,135.0,581.0,13.0,17.0,45.0,47.0,32.0,393.0
단백질,1.97,0.02,0.01,2.83,15.12,7.0,9.88,4.8,1.88,0.36,...,13.73,9.88,4.2,23.44,0.8,0.59,0.29,1.57,3.09,6.8
지방,0.57,0.02,0.011818,0.38,13.46,27.8,4.81,4.8,0.36,0.05,...,7.25,2.04,0.7,49.96,0.0,0.05,0.04,0.29,0.34,0.2
탄수화물,6.24,0.48,9.03,33.76,3.79,58.8,39.18,25.0,3.48,2.42,...,18.94,27.0,29.1,20.09,3.1,3.64,12.24,11.01,6.14,86.8
당,2.87,0.01,7.691,0.03,0.2,NaN,21.08,NaN,1.22,0.55,...,5.45,14.82,NaN,6.82,NaN,0.0,8.3,9.08,0.33,NaN
칼슘,51.0,1.0,2.909091,9.0,72.0,136.0,62.0,20.0,95.0,21.0,...,79.0,29.0,21.0,368.0,18.0,89.0,2.0,6.0,201.0,18.0
철,0.51,0.0,0.04,0.24,2.27,1.8,1.76,4.5,3.41,0.16,...,2.07,1.05,2.1,4.76,0.5,0.31,0.06,0.26,1.32,0.6
인,53.0,2.0,3.727273,39.0,235.0,239.0,137.0,67.0,50.0,8.0,...,218.0,163.0,123.0,523.0,23.0,11.0,13.0,51.0,77.0,74.0
칼륨,355.0,47.0,4.545455,41.0,152.0,44.0,472.0,106.0,591.0,42.0,...,539.0,172.0,356.0,780.0,195.0,364.0,124.0,450.0,339.0,84.0
나트륨,593.0,0.0,6.090909,159.0,162.0,634.0,2619.0,330.0,17.0,637.0,...,4339.0,2278.0,1.0,6.0,3.0,1.0,0.0,2.0,2.0,6.0
비타민a,29.0,0.0,0.0,0.0,140.0,0.0,51.0,39.0,239.0,0.0,...,0.0,38.0,12.0,1.0,1.0,9.0,0.0,1.0,303.0,0.0
티아민,0.052,0.0,0.026909,0.026,0.069,0.05,0.128,0.32,0.016,0.013,...,0.588,0.141,0.08,0.029,0.1,0.006,0.022,0.006,0.085,0.07
리보플라빈,0.106,0.03,0.040182,0.014,0.513,0.25,0.108,0.15,0.136,0.015,...,0.837,0.047,0.03,1.546,0.02,0.016,0.063,0.08,0.244,0.03
니아신,0.561,0.111,0.046091,0.21,0.054,1.7,1.079,0.9,0.612,0.173,...,1.257,0.746,1.6,3.789,0.5,0.179,0.139,0.184,0.054,1.5
엽산,55.0,1.0,0.0,9.0,160.0,NaN,33.0,NaN,64.0,21.0,...,139.0,13.0,NaN,74.0,NaN,4.0,0.0,17.0,68.0,NaN
비타민c,3.61,0.0,3.791818,0.0,0.0,0.0,0.0,0.0,0.24,18.42,...,11.2,12.77,0.0,0.0,0.0,0.0,2.65,21.0,0.0,0.0

In [48]:
# 섭취량 - 기준량
male20_diff_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/male_20s_standard.csv"
female20_diff_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/female_20s_standard.csv"
male30_diff_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/male_30s_standard.csv"
female30_diff_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/female_30s_standard.csv"

In [49]:
male20_diff = pd.read_csv(male20_diff_path)
male20_diff.drop(columns="Unnamed: 0",inplace=True)
female20_diff = pd.read_csv(female20_diff_path)
female20_diff.drop(columns="Unnamed: 0",inplace=True)
male30_diff = pd.read_csv(male30_diff_path)
male30_diff.drop(columns="Unnamed: 0",inplace=True)
female30_diff = pd.read_csv(female30_diff_path)
female30_diff.drop(columns="Unnamed: 0",inplace=True)

In [50]:
male20_diff = male20_diff.sort_values(by="섭취량-기준").head()
female20_diff = female20_diff.sort_values(by="섭취량-기준").head()

male30_diff = male30_diff.sort_values(by="섭취량-기준").head()
female30_diff = female30_diff.sort_values(by="섭취량-기준").head()

In [51]:
male20_diff

         영양소  성별     연령  기준 섭취량       평균  섭취량-기준
12    칼륨  남자  19-29  3500.0  2790.23 -709.77
5   비타민a  남자  19-29   800.0   459.24 -340.76
7     에너지  남자  19-29  2600.0  2298.76 -301.24
13    칼슘  남자  19-29   800.0   533.43 -266.57
8     엽산  남자  19-29   400.0   290.20 -109.80

In [52]:
female20_diff

         영양소  성별     연령  기준 섭취량       평균   섭취량-기준
12    칼륨  남자  30-49  3500.0  2052.97 -1447.03
7     에너지  남자  30-49  2500.0  1634.49  -865.51
5   비타민a  남자  30-49   800.0   367.07  -432.93
13    칼슘  남자  30-49   800.0   439.14  -360.86
8     엽산  남자  30-49   400.0   220.95  -179.05

In [53]:
male30_diff

         영양소  성별     연령  기준 섭취량       평균  섭취량-기준
12    칼륨  여자  19-29  3500.0  3174.09 -325.91
5   비타민a  여자  19-29   650.0   427.46 -222.54
13    칼슘  여자  19-29   700.0   540.24 -159.76
8     엽산  여자  19-29   400.0   335.48  -64.52
6   비타민c  여자  19-29   100.0    69.87  -30.13

In [54]:
female30_diff

         영양소  성별     연령  기준 섭취량       평균   섭취량-기준
12    칼륨  여자  30-49  3500.0  2481.38 -1018.62
5   비타민a  여자  30-49   650.0   383.44  -266.56
13    칼슘  여자  30-49   700.0   447.31  -252.69
7     에너지  여자  30-49  1900.0  1666.40  -233.60
8     엽산  여자  30-49   400.0   268.20  -131.80

In [55]:
# 선호 차이 큰 음식
prefer_20s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_20s_common.csv" 
prefer_30s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_30s_common.csv"

In [56]:
prefer_20s = pd.read_csv(prefer_20s_path)
prefer_30s = pd.read_csv(prefer_30s_path)
prefer_20s.drop(columns="Unnamed: 0",inplace=True)
prefer_30s.drop(columns="Unnamed: 0",inplace=True)

In [57]:
prefer_20s = prefer_20s[prefer_20s['abs(남자-여자 순위 차이)'] > 4]
prefer_20s.sort_values(by="abs(남자-여자 순위 차이)",ascending=False,inplace=True)
save_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_20s_common_2.csv"
prefer_20s.to_csv(save_path)

In [58]:
prefer_30s = prefer_30s[prefer_30s['abs(남자-여자 순위 차이)'] > 4]
prefer_30s.sort_values(by="abs(남자-여자 순위 차이)",ascending=False,inplace=True)
save_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_30s_common_2.csv"
prefer_30s.to_csv(save_path)

<ipython-input-58-6237e75f5060>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefer_30s.sort_values(by="abs(남자-여자 순위 차이)",ascending=False,inplace=True)

In [59]:
food_20s = prefer_20s.loc[:,["19-29 음식","남자-여자 순위 차이"]]
food_20s.sort_values(by="남자-여자 순위 차이",inplace=True)
food_20s.set_index("19-29 음식",inplace=True)

In [60]:
# 선호 차이 큰 음식들 뽑아서 성별로 분리 

path1 = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_20s_common_2.csv"
prefer_rank_20 = pd.read_csv(path1)
prefer_rank_20.drop(columns="Unnamed: 0",inplace=True)

path2 = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_30s_common_2.csv"
prefer_rank_30 = pd.read_csv(path2)
prefer_rank_30.drop(columns="Unnamed: 0",inplace=True)

In [61]:
prefer_rank_20 = prefer_rank_20.loc[:,["19-29 음식","순위_x","순위_y","남자-여자 순위 차이","abs(남자-여자 순위 차이)"]]
prefer_rank_20.rename(columns={"19-29 음식":"음식","순위_x":"남성 순위","순위_y":"여성 순위"},inplace=True)
prefer_rank_20["선호 성별"] = prefer_rank_20["남자-여자 순위 차이"].apply(lambda x: "남" if x<0 else "여")
prefer_rank_20.to_csv("/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/prefer_20s.csv")

prefer_rank_30 = prefer_rank_30.loc[:,["30-49 음식","순위_x","순위_y","남자-여자 순위 차이","abs(남자-여자 순위 차이)"]]
prefer_rank_30.rename(columns={"30-49 음식":"음식","순위_x":"남성 순위","순위_y":"여성 순위"},inplace=True)
prefer_rank_30["선호 성별"] = prefer_rank_30["남자-여자 순위 차이"].apply(lambda x: "남" if x<0 else "여")
prefer_rank_30.to_csv("/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/prefer_30s.csv")

In [62]:
female20_prefer = prefer_rank_20[prefer_rank_20["선호 성별"]=="여"]
male20_prefer = prefer_rank_20[prefer_rank_20["선호 성별"]=="남"]

female30_prefer = prefer_rank_30[prefer_rank_30["선호 성별"]=="여"]
male30_prefer = prefer_rank_30[prefer_rank_30["선호 성별"]=="남"]

In [63]:
female20_prefer

           음식  남성 순위  여성 순위  남자-여자 순위 차이  abs(남자-여자 순위 차이) 선호 성별
0          케잌   70.0   34.0         36.0              36.0     여
3          사과   57.0   24.0         33.0              33.0     여
4         콩나물   60.0   28.0         32.0              32.0     여
5        요구르트   48.0   17.0         31.0              31.0     여
6        스파게티   69.0   38.0         31.0              31.0     여
7         시리얼   61.0   31.0         30.0              30.0     여
8         고구마   76.0   47.0         29.0              29.0     여
12         만두   45.0   21.0         24.0              24.0     여
15          빵   29.0    9.0         20.0              20.0     여
16        비빔밥   77.0   58.0         19.0              19.0     여
17        떡볶이   31.0   14.0         17.0              17.0     여
19      토마토케챱   46.0   30.0         16.0              16.0     여
22         간장   47.0   32.0         15.0              15.0     여
23  오이지/오이장아찌   58.0   43.0         15.0              15.0     여
24        김구이   27.0   12.0         15.0              15.0     여
27       열무김치   41.0   29.0         12.0              12.0     여
28         소금   56.0   44.0         12.0              12.0     여
29         치즈   74.0   62.0         12.0              12.0     여
33         달걀   54.0   45.0          9.0               9.0     여
35      쇠고기구이   62.0   54.0          8.0               8.0     여
39          귤   34.0   27.0          7.0               7.0     여
40      삼겹살구이   33.0   26.0          7.0               7.0     여
41         우유   14.0    8.0          6.0               6.0     여
43       샌드위치   23.0   18.0          5.0               5.0     여
44         젤리   78.0   73.0          5.0               5.0     여

In [64]:
male20_prefer

        음식  남성 순위  여성 순위  남자-여자 순위 차이  abs(남자-여자 순위 차이) 선호 성별
1       마늘   16.0   52.0        -36.0              36.0     남
2      불고기   36.0   70.0        -34.0              34.0     남
9   돼지고기볶음   26.0   53.0        -27.0              27.0     남
10     단무지   12.0   37.0        -25.0              25.0     남
11      양파   32.0   56.0        -24.0              24.0     남
13    멸치볶음   18.0   42.0        -24.0              24.0     남
14      고추   43.0   64.0        -21.0              21.0     남
18     토마토   51.0   68.0        -17.0              17.0     남
20      맥주   17.0   33.0        -16.0              16.0     남
21     햄버거   19.0   35.0        -16.0              16.0     남
25    된장찌개   25.0   39.0        -14.0              14.0     남
26  소스, 카레   52.0   65.0        -13.0              13.0     남
30     미역국   40.0   51.0        -11.0              11.0     남
31      피자   30.0   40.0        -10.0              10.0     남
32     고추장   37.0   46.0         -9.0               9.0     남
34      상추   11.0   20.0         -9.0               9.0     남
36      수박   73.0   81.0         -8.0               8.0     남
37   고등어구이   42.0   50.0         -8.0               8.0     남
38      소주   28.0   36.0         -8.0               8.0     남
42     쵸컬릿   44.0   49.0         -5.0               5.0     남

In [65]:
male20_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/male20_prefer.csv"
female20_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/female20_prefer.csv"
male30_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/male30_prefer.csv"
female30_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/female30_prefer.csv"

female20_prefer.to_csv(female20_path)
male20_prefer.to_csv(male20_path)

female30_prefer.to_csv(female30_path)
male30_prefer.to_csv(male30_path)

In [74]:
# 여성 선호 음식 상위 10개와 결핍영양분보충 음식 상위 10개 비교 
f_prefer = ["케잌","요구르트","스파게티","시리얼","만두"]
# 케잌의 영양성분과 결핍영양분의 상관관계 

for name in f_prefer:
  # 선호음식의 영양성분 뽑기 
  # 결핍 영양분 정보 
  ne = female20_diff.loc[:,["영양소","섭취량-기준"]]

  tmp = 
  new_df = pd.DataFrame(
      "칼륨":food_db[name]["칼륨"],

  )
  food_db[name]["칼륨"]
  new_df = pd.concat([new_df,food_db[name]["에너지"]])
  # for n in 
  print(new_df)
  # new_df.sort_values(ascending=False).head()

TypeError: ignored