In [51]:
import pandas as pd

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [53]:
# 20대 남녀 평균 영양섭취량 df
female_20s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/final/nutrition_amount_for_female_20s.csv" 
male_20s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/final/nutrition_amount_for_male_20s.csv"

female_20s = pd.read_csv(female_20s_path).iloc[:,:3]
male_20s = pd.read_csv(male_20s_path).iloc[:,:3]

In [54]:
female_20s.drop(columns="Unnamed: 0",inplace=True)

In [55]:
male_20s.drop(columns="Unnamed: 0",inplace=True)

In [56]:
female_20s

      영양소       평균
0     에너지  1634.49
1     단백질    59.49
2      지방    51.17
3    탄수화물   218.76
4       당    55.51
5      칼슘   439.14
6       인   855.21
7       철     8.66
8     나트륨  2546.30
9      칼륨  2052.97
10   비타민a   367.07
11    티아민     1.03
12  리보플라빈     1.52
13    니아신    10.73
14   비타민c    47.66
15     엽산   220.95

In [57]:
# 한국인 영양 섭취 기준 
standard_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/nutrition_standard_final.xlsx"
standard = pd.read_excel(standard_path,sheet_name="nutrition_standard_final.xlsx")
standard.drop(columns="Unnamed: 0",inplace=True)
standard

           영양소  성별     연령  기준 섭취량
0      나트륨  남자  19-29  1500.0
1      나트륨  남자  30-49  1500.0
2      나트륨  여자  19-29  1500.0
3      나트륨  여자  30-49  1500.0
4          당  남자  19-29   229.0
..         ...  ..    ...     ...
59  탄수화물  여자  30-49   130.0
60      칼슘  남자  19-29   800.0
61      칼슘  남자  30-49   800.0
62      칼슘  여자  19-29   700.0
63      칼슘  여자  30-49   700.0

[64 rows x 4 columns]

In [58]:
# 연령, 성별 나누기 
male_20s_standard = []
female_20s_standard = []

male_30s_standard = []
female_30s_standard = []

for i in range(len(standard)):
  # print(standard.iloc[0,:])
  row = standard.iloc[i,:]
  if i%4 == 0:
    male_20s_standard.append(row.to_list())
  elif i%4 == 2:
    female_20s_standard.append(row.to_list())
  # if i%4 == 1:
  #   male_30s_standard.append(row.to_list())
  # elif i%4 == 3:
  #   female_30s_standard.append(row.to_list())
print(male_20s_standard)
print(female_20s_standard)
# print(male_30s_standard)
# print(female_30s_standard)

[['나트륨', '남자', '19-29', 1500.0], ['당', '남자', '19-29', 229.0], ['에너지', '남자', '19-29', 2600.0], ['인', '남자', '19-29', 700.0], ['엽산', '남자', '19-29', 400.0], ['비타민a', '남자', '19-29', 800.0], ['지방', '남자', '19-29', 75.0], ['단백질', '남자', '19-29', 65.0], ['리보플라빈', '남자', '19-29', 1.5], ['비타민c', '남자', '19-29', 100.0], ['니아신', '남자', '19-29', 16.0], ['철', '남자', '19-29', 10.0], ['칼륨', '남자', '19-29', 3500.0], ['티아민', '남자', '19-29', 1.2], ['탄수화물', '남자', '19-29', 130.0], ['칼슘', '남자', '19-29', 800.0]]
[['나트륨', '여자', '19-29', 1500.0], ['당', '여자', '19-29', 163.0], ['에너지', '여자', '19-29', 2000.0], ['인', '여자', '19-29', 700.0], ['엽산', '여자', '19-29', 400.0], ['비타민a', '여자', '19-29', 650.0], ['지방', '여자', '19-29', 59.0], ['단백질', '여자', '19-29', 55.0], ['리보플라빈', '여자', '19-29', 1.2], ['비타민c', '여자', '19-29', 100.0], ['니아신', '여자', '19-29', 14.0], ['철', '여자', '19-29', 14.0], ['칼륨', '여자', '19-29', 3500.0], ['티아민', '여자', '19-29', 1.1], ['탄수화물', '여자', '19-29', 130.0], ['칼슘', '여자', '19-29', 700.0]]

In [59]:
male_20s_standard = pd.DataFrame(male_20s_standard)
female_20s_standard = pd.DataFrame(female_20s_standard)
# male_30s_standard = pd.DataFrame(male_30s_standard)
# female_30s_standard = pd.DataFrame(female_30s_standard)

In [60]:
male_20s_standard

               0   1      2       3
0        나트륨  남자  19-29  1500.0
1            당  남자  19-29   229.0
2         에너지  남자  19-29  2600.0
3            인  남자  19-29   700.0
4         엽산  남자  19-29   400.0
5       비타민a  남자  19-29   800.0
6          지방  남자  19-29    75.0
7      단백질  남자  19-29    65.0
8   리보플라빈  남자  19-29     1.5
9       비타민c  남자  19-29   100.0
10       니아신  남자  19-29    16.0
11           철  남자  19-29    10.0
12        칼륨  남자  19-29  3500.0
13       티아민  남자  19-29     1.2
14    탄수화물  남자  19-29   130.0
15        칼슘  남자  19-29   800.0

In [61]:
cols = ["영양소","성별","연령","기준 섭취량"]
male_20s_standard.columns = cols
female_20s_standard.columns = cols
# male_30s_standard.columns = cols
# female_30s_standard.columns = cols

In [62]:
male_20s.sort_values(by="영양소",inplace=True)
male_20s.reset_index(drop=True, inplace=True)

female_20s.sort_values(by="영양소",inplace=True)
female_20s.reset_index(drop=True, inplace=True)

# male_30s.sort_values(by="영양소",inplace=True)
# male_30s.reset_index(drop=True, inplace=True)

# female_30s.sort_values(by="영양소",inplace=True)
# female_30s.reset_index(drop=True, inplace=True)

In [63]:
male_20s

      영양소       평균
0     나트륨  3823.90
1     니아신    16.04
2     단백질    92.23
3       당    62.84
4   리보플라빈     2.08
5    비타민a   459.24
6    비타민c    69.93
7     에너지  2298.76
8      엽산   290.20
9       인  1211.56
10     지방    68.58
11      철    12.18
12     칼륨  2790.23
13     칼슘   533.43
14   탄수화물   298.82
15    티아민     1.50

In [64]:
# male_20s.set_index("영양소",inplace=True)
# female_20s.set_index("영양소",inplace=True)
# male_30s.set_index("영양소",inplace=True)
# female_30s.set_index("영양소",inplace=True)

In [65]:
male_20s_standard.sort_values(by="영양소",inplace=True)
male_20s_standard.reset_index(drop=True, inplace=True)

female_20s_standard.sort_values(by="영양소",inplace=True)
female_20s_standard.reset_index(drop=True, inplace=True)

# male_30s_standard.sort_values(by="영양소",inplace=True)
# male_30s_standard.reset_index(drop=True, inplace=True)

# female_30s_standard.sort_values(by="영양소",inplace=True)
# female_30s_standard.reset_index(drop=True, inplace=True)

In [66]:
male_20s_standard.set_index("영양소", inplace=True)
female_20s_standard.set_index("영양소", inplace=True)
# male_30s_standard.set_index("영양소", inplace=True)
# female_30s_standard.set_index("영양소", inplace=True)

In [67]:
male_20s_standard

              성별     연령  기준 섭취량
영양소
나트륨       남자  19-29  1500.0
니아신       남자  19-29    16.0
단백질     남자  19-29    65.0
당           남자  19-29   229.0
리보플라빈  남자  19-29     1.5
비타민a      남자  19-29   800.0
비타민c      남자  19-29   100.0
에너지        남자  19-29  2600.0
엽산        남자  19-29   400.0
인           남자  19-29   700.0
지방         남자  19-29    75.0
철           남자  19-29    10.0
칼륨        남자  19-29  3500.0
칼슘        남자  19-29   800.0
탄수화물    남자  19-29   130.0
티아민       남자  19-29     1.2

In [68]:
male_20s

      영양소       평균
0     나트륨  3823.90
1     니아신    16.04
2     단백질    92.23
3       당    62.84
4   리보플라빈     2.08
5    비타민a   459.24
6    비타민c    69.93
7     에너지  2298.76
8      엽산   290.20
9       인  1211.56
10     지방    68.58
11      철    12.18
12     칼륨  2790.23
13     칼슘   533.43
14   탄수화물   298.82
15    티아민     1.50

In [69]:
male_20s_standard["평균"] = male_20s["평균"].to_list()
female_20s_standard["평균"] = female_20s["평균"].to_list()
# male_30s_standard["평균"] = male_30s["평균"].to_list()
# female_30s_standard["평균"] = female_30s["평균"].to_list()

In [70]:
male_20s_standard["섭취량-기준"] = male_20s_standard["평균"] - male_20s_standard["기준 섭취량"]
female_20s_standard["섭취량-기준"] = female_20s_standard["평균"] - female_20s_standard["기준 섭취량"]
# male_30s_standard["섭취량-기준"] = male_30s_standard["평균"] - male_30s_standard["기준 섭취량"]
# female_30s_standard["섭취량-기준"] = female_30s_standard["평균"] - female_30s_standard["기준 섭취량"]

In [71]:
male_20s_standard

              성별     연령  기준 섭취량       평균   섭취량-기준
영양소
나트륨       남자  19-29  1500.0  3823.90  2323.90
니아신       남자  19-29    16.0    16.04     0.04
단백질     남자  19-29    65.0    92.23    27.23
당           남자  19-29   229.0    62.84  -166.16
리보플라빈  남자  19-29     1.5     2.08     0.58
비타민a      남자  19-29   800.0   459.24  -340.76
비타민c      남자  19-29   100.0    69.93   -30.07
에너지        남자  19-29  2600.0  2298.76  -301.24
엽산        남자  19-29   400.0   290.20  -109.80
인           남자  19-29   700.0  1211.56   511.56
지방         남자  19-29    75.0    68.58    -6.42
철           남자  19-29    10.0    12.18     2.18
칼륨        남자  19-29  3500.0  2790.23  -709.77
칼슘        남자  19-29   800.0   533.43  -266.57
탄수화물    남자  19-29   130.0   298.82   168.82
티아민       남자  19-29     1.2     1.50     0.30

In [72]:
# male_30s_standard.sort_values(by="섭취량-기준",ascending=True)

AttributeError: ignored

In [ ]:
# female_30s_standard.sort_values(by="섭취량-기준",ascending=True)

In [73]:
base_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData"
male_20s_standard.to_csv(base_path+"/male_20s_standard.csv")
female_20s_standard.to_csv(base_path+"/female_20s_standard.csv")
# male_30s_standard.to_csv(base_path+"/male_30s_standard.csv")
# female_30s_standard.to_csv(base_path+"/female_30s_standard.csv")

In [74]:
male_20s_standard

              성별     연령  기준 섭취량       평균   섭취량-기준
영양소
나트륨       남자  19-29  1500.0  3823.90  2323.90
니아신       남자  19-29    16.0    16.04     0.04
단백질     남자  19-29    65.0    92.23    27.23
당           남자  19-29   229.0    62.84  -166.16
리보플라빈  남자  19-29     1.5     2.08     0.58
비타민a      남자  19-29   800.0   459.24  -340.76
비타민c      남자  19-29   100.0    69.93   -30.07
에너지        남자  19-29  2600.0  2298.76  -301.24
엽산        남자  19-29   400.0   290.20  -109.80
인           남자  19-29   700.0  1211.56   511.56
지방         남자  19-29    75.0    68.58    -6.42
철           남자  19-29    10.0    12.18     2.18
칼륨        남자  19-29  3500.0  2790.23  -709.77
칼슘        남자  19-29   800.0   533.43  -266.57
탄수화물    남자  19-29   130.0   298.82   168.82
티아민       남자  19-29     1.2     1.50     0.30

In [75]:
female_20s_standard

              성별     연령  기준 섭취량       평균   섭취량-기준
영양소
나트륨       여자  19-29  1500.0  2546.30  1046.30
니아신       여자  19-29    14.0    10.73    -3.27
단백질     여자  19-29    55.0    59.49     4.49
당           여자  19-29   163.0    55.51  -107.49
리보플라빈  여자  19-29     1.2     1.52     0.32
비타민a      여자  19-29   650.0   367.07  -282.93
비타민c      여자  19-29   100.0    47.66   -52.34
에너지        여자  19-29  2000.0  1634.49  -365.51
엽산        여자  19-29   400.0   220.95  -179.05
인           여자  19-29   700.0   855.21   155.21
지방         여자  19-29    59.0    51.17    -7.83
철           여자  19-29    14.0     8.66    -5.34
칼륨        여자  19-29  3500.0  2052.97 -1447.03
칼슘        여자  19-29   700.0   439.14  -260.86
탄수화물    여자  19-29   130.0   218.76    88.76
티아민       여자  19-29     1.1     1.03    -0.07

In [ ]:
# 부족한 영양성분과 선호차이나는 음식들 비교

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
# 선호차이나는 음식 리스트
# 20대 
data_20s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_20s_common.csv"
data_20s = pd.read_csv(data_20s_path)
data_20s.drop(columns="Unnamed: 0",inplace=True)
data_20s = data_20s[data_20s.loc[:,"abs(남자-여자 순위 차이)"] > 4]
data_20s.sort_values(by="abs(남자-여자 순위 차이)",ascending=False,inplace=True)
data_20s

In [ ]:
# 선호차이나는 음식 리스트
# 30대 
data_30s_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/data_30s_common.csv"
data_30s = pd.read_csv(data_30s_path)
data_30s.drop(columns="Unnamed: 0",inplace=True)
data_30s = data_30s[data_30s.loc[:,"abs(남자-여자 순위 차이)"] > 4]
data_30s.sort_values(by="abs(남자-여자 순위 차이)",ascending=False,inplace=True)
data_30s

In [ ]:
# 음식성분 db와 비교
db_path = "/content/drive/MyDrive/Tacademy ASAC/EDA Project/finishedData/식품db.xlsx"
food_db = pd.read_excel(db_path,sheet_name="시트1")

In [ ]:
food_db

In [ ]:
male_30s_standard["섭취량-기준"]

In [ ]:
food_db[food_db["식품명"]=="돼지고기볶음"]

In [ ]:
# 음식 성분 db 값 - (섭취량-기준) 한 값이 음수인 것 찾기 
tmp = food_db[food_db["식품명"]=="돼지고기볶음"]
standard = male_30s_standard.iloc[:,[0,-1]]
tmp=tmp.transpose()
tmp

In [ ]:
standard.info()

In [ ]:
tmp.reset_index(inplace=True)
tmp.rename(columns=tmp.iloc[0],inplace=True)

In [ ]:
tmp.drop(index=0,axis=0,inplace=True)

In [ ]:
tmp

In [ ]:
tmp.rename(columns={"식품명":"영양소","돼지고기볶음":"성분량"},inplace=True)

In [ ]:
tmp.reset_index(drop=True,inplace=True)

In [ ]:
tmp.info()

In [ ]:
tmp["성분량"]=tmp["성분량"].astype("float")

In [ ]:
# 성분량 내림차순 결과와 섭취-기준 오름차순 결과 상에서
# 겹치는 성분들이 있다면 결핍 영양분을 보충하는 것 
tmp.sort_values(by="성분량",ascending=False)

In [ ]:
standard.sort_values(by="섭취량-기준")